# 로컬 profile 적용되는 config파일
server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://eureka1:8761/eureka/

test:
  profile: trade
greeting:
  message: trade config test message

discode:
  webhook: https://discord.com/api/webhooks/994567617052422184/whINZv_sW1i6Zr0ohGokuif0XyefGCNOnIiauHsxKpcwnbE6N6PDO6R_XU7Z5ZX0xZRs